site_name: reconciler
site_description: Python utilities to reconcile Pandas DataFrames.
site_author: jvfe
site_url: https://jvfe.github.io/reconciler/
nav:
    - Home: index.md
    - Installation: installing.md
    - Version history: history.md
    - Contributing: 
        - Contribution guide: contributing.md
        - Contributors: authors.md
    - Example usage:
      - Reconciling cell types: examples/reconcile_cell_types.md
    - Reference:
      - Main module: reference/reconcile.md
      - Web utilities module: reference/webutils.md
      - General utilities module: reference/utils.md
repo_url: https://github.com/jvfe/reconciler
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings
